"""add registered name e alterado name para hotel_name

Revision ID: 0e5dc10ba1a3
Revises: ec74adf32f32
Create Date: 2024-11-17 19:35:20.228881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e5dc10ba1a3'
down_revision: Union[str, None] = 'ec74adf32f32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('hotel_name', sa.String(), nullable=False))
    op.add_column('hotels', sa.Column('registered_name', sa.String(), nullable=False))
    op.drop_column('hotels', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('hotels', 'registered_name')
    op.drop_column('hotels', 'hotel_name')
    # ### end Alembic commands ###
