"""adicionado atributos Address, redes sociais, wifi e comodidades em entidade hotel

Revision ID: ec74adf32f32
Revises: fa5cad800e1f
Create Date: 2024-10-13 12:36:22.788679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec74adf32f32'
down_revision: Union[str, None] = 'fa5cad800e1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('street_address', sa.String(), nullable=False))
    op.add_column('hotels', sa.Column('number_address', sa.String(), nullable=False))
    op.add_column('hotels', sa.Column('city', sa.String(), nullable=False))
    op.add_column('hotels', sa.Column('state', sa.String(), nullable=False))
    op.add_column('hotels', sa.Column('cep', sa.String(), nullable=False))
    op.add_column('hotels', sa.Column('social_media', sa.String(), nullable=True))
    op.add_column('hotels', sa.Column('wifi_network', sa.String(), nullable=True))
    op.add_column('hotels', sa.Column('wifi_password', sa.String(), nullable=True))
    op.add_column('hotels', sa.Column('amenity', sa.String(), nullable=True))
    op.add_column('hotels', sa.Column('start_time', sa.String(), nullable=True))
    op.add_column('hotels', sa.Column('end_time', sa.String(), nullable=True))
    op.alter_column('hotels', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('hotels', 'email_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('hotels', 'cnpj',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hotels', 'cnpj',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('hotels', 'email_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('hotels', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('hotels', 'end_time')
    op.drop_column('hotels', 'start_time')
    op.drop_column('hotels', 'amenity')
    op.drop_column('hotels', 'wifi_password')
    op.drop_column('hotels', 'wifi_network')
    op.drop_column('hotels', 'social_media')
    op.drop_column('hotels', 'cep')
    op.drop_column('hotels', 'state')
    op.drop_column('hotels', 'city')
    op.drop_column('hotels', 'number_address')
    op.drop_column('hotels', 'street_address')
    # ### end Alembic commands ###
