"""inicial

Revision ID: fa5cad800e1f
Revises: 
Create Date: 2024-09-21 11:19:28.483789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa5cad800e1f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('department_id', sa.Integer(), nullable=True))
    op.drop_constraint('requests_sector_id_fkey', 'requests', type_='foreignkey')
    op.create_foreign_key(None, 'requests', 'departments', ['department_id'], ['id'])
    op.drop_column('requests', 'sector_id')
    op.add_column('services', sa.Column('department_id', sa.Integer(), nullable=True))
    op.drop_constraint('services_sector_id_fkey', 'services', type_='foreignkey')
    op.create_foreign_key(None, 'services', 'departments', ['department_id'], ['id'])
    op.drop_column('services', 'sector_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('sector_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.create_foreign_key('services_sector_id_fkey', 'services', 'departments', ['sector_id'], ['id'])
    op.drop_column('services', 'department_id')
    op.add_column('requests', sa.Column('sector_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.create_foreign_key('requests_sector_id_fkey', 'requests', 'departments', ['sector_id'], ['id'])
    op.drop_column('requests', 'department_id')
    # ### end Alembic commands ###
